# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Sun Oct 12 11:38:52 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(533, 346)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.username = QtGui.QLineEdit(self.centralwidget)
        self.username.setObjectName(_fromUtf8("username"))
        self.horizontalLayout_3.addWidget(self.username)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.password = QtGui.QLineEdit(self.centralwidget)
        self.password.setEchoMode(QtGui.QLineEdit.Password)
        self.password.setObjectName(_fromUtf8("password"))
        self.horizontalLayout_3.addWidget(self.password)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.note_name = QtGui.QLineEdit(self.centralwidget)
        self.note_name.setMinimumSize(QtCore.QSize(120, 0))
        self.note_name.setText(_fromUtf8(""))
        self.note_name.setObjectName(_fromUtf8("note_name"))
        self.horizontalLayout_3.addWidget(self.note_name)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.note_folder = QtGui.QLineEdit(self.centralwidget)
        self.note_folder.setObjectName(_fromUtf8("note_folder"))
        self.horizontalLayout_4.addWidget(self.note_folder)
        self.browser_dir = QtGui.QPushButton(self.centralwidget)
        self.browser_dir.setObjectName(_fromUtf8("browser_dir"))
        self.horizontalLayout_4.addWidget(self.browser_dir)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.textEdit = Qsci.QsciScintilla(self.centralwidget)
        self.textEdit.setToolTip(_fromUtf8(""))
        self.textEdit.setWhatsThis(_fromUtf8(""))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_2.addWidget(self.textEdit)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.recorded_minutes_and_seconds = QtGui.QLabel(self.centralwidget)
        self.recorded_minutes_and_seconds.setObjectName(_fromUtf8("recorded_minutes_and_seconds"))
        self.horizontalLayout_5.addWidget(self.recorded_minutes_and_seconds)
        self.start_button = QtGui.QPushButton(self.centralwidget)
        self.start_button.setObjectName(_fromUtf8("start_button"))
        self.horizontalLayout_5.addWidget(self.start_button)
        self.resume_button = QtGui.QPushButton(self.centralwidget)
        self.resume_button.setObjectName(_fromUtf8("resume_button"))
        self.horizontalLayout_5.addWidget(self.resume_button)
        self.pause_button = QtGui.QPushButton(self.centralwidget)
        self.pause_button.setObjectName(_fromUtf8("pause_button"))
        self.horizontalLayout_5.addWidget(self.pause_button)
        self.stop_button = QtGui.QPushButton(self.centralwidget)
        self.stop_button.setObjectName(_fromUtf8("stop_button"))
        self.horizontalLayout_5.addWidget(self.stop_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.textEdit_2 = Qsci.QsciScintilla(self.centralwidget)
        self.textEdit_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textEdit_2.setToolTip(_fromUtf8(""))
        self.textEdit_2.setWhatsThis(_fromUtf8(""))
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.verticalLayout_2.addWidget(self.textEdit_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 533, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menubar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.start = QtGui.QAction(MainWindow)
        self.start.setObjectName(_fromUtf8("start"))
        self.pause = QtGui.QAction(MainWindow)
        self.pause.setObjectName(_fromUtf8("pause"))
        self.resume = QtGui.QAction(MainWindow)
        self.resume.setObjectName(_fromUtf8("resume"))
        self.stop = QtGui.QAction(MainWindow)
        self.stop.setObjectName(_fromUtf8("stop"))
        self.open = QtGui.QAction(MainWindow)
        self.open.setObjectName(_fromUtf8("open"))
        self.exit = QtGui.QAction(MainWindow)
        self.exit.setObjectName(_fromUtf8("exit"))
        self.menu.addAction(self.open)
        self.menu.addAction(self.exit)
        self.menu_2.addAction(self.start)
        self.menu_2.addAction(self.pause)
        self.menu_2.addAction(self.resume)
        self.menu_2.addAction(self.stop)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Username:", None))
        self.label_2.setText(_translate("MainWindow", "Password:", None))
        self.label_4.setText(_translate("MainWindow", "Note name:", None))
        self.label_3.setText(_translate("MainWindow", "Path:", None))
        self.note_folder.setText(_translate("MainWindow", "g:\\tmp\\", None))
        self.browser_dir.setText(_translate("MainWindow", "Browser", None))
        self.recorded_minutes_and_seconds.setText(_translate("MainWindow", "000:00", None))
        self.start_button.setText(_translate("MainWindow", "Start", None))
        self.resume_button.setText(_translate("MainWindow", "Resume", None))
        self.pause_button.setText(_translate("MainWindow", "Pause", None))
        self.stop_button.setText(_translate("MainWindow", "Stop", None))
        self.menu.setTitle(_translate("MainWindow", "文件", None))
        self.menu_2.setTitle(_translate("MainWindow", "动作", None))
        self.start.setText(_translate("MainWindow", "开始", None))
        self.pause.setText(_translate("MainWindow", "暂停", None))
        self.resume.setText(_translate("MainWindow", "继续", None))
        self.stop.setText(_translate("MainWindow", "停止", None))
        self.open.setText(_translate("MainWindow", "打开", None))
        self.exit.setText(_translate("MainWindow", "退出", None))

from PyQt4 import Qsci
